language: cpp
sudo: false

notifications:
  email: false

matrix:
  include:

    # Linux C++14 GCC builds
    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

script:
- cmake -H. -B_build 
- cmake --build _build
- _build/pack artifacts/person1.json
- _build/unpack artifacts/person1.json
